# Generated by Django 2.0.3 on 2018-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=100)),
                ('ename', models.CharField(default='', max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
