# Generated by Django 2.0.3 on 2018-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='isDel',
            field=models.BooleanField(default=False),
        ),
    ]
